name: Run Selenium Tests in Docker

on: [push]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Build Docker image
        run: docker build -t selenium-tests .

      - name: Run tests in Docker
        run: docker run --name selenium-container selenium-tests

      - name: Copy Allure results from container
        if: always()
        run: |
          docker cp selenium-container:/app/allure-results ./allure-results || true

      - name: Upload Allure results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results